freepage_id:
  url:     /freepage/:id
  class:   sfDoctrineRoute
  options: { model: Freepage, type: object, method: findForMobileRoute }
  params:  { module: freepage, action: index }
  requirements:
    id:    \d+

freepage_nodefaults:
  url:     /freepage/*
  params:  { module: default, action: error }
